# Generated by Django 4.0.2 on 2022-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuvraj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
